export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './bonsAchatVente.service';
import { BonsAchatVenteService } from './bonsAchatVente.service';
export * from './caisseJourController.service';
import { CaisseJourControllerService } from './caisseJourController.service';
export * from './dettesController.service';
import { DettesControllerService } from './dettesController.service';
export * from './fluxNormalController.service';
import { FluxNormalControllerService } from './fluxNormalController.service';
export * from './mesInfos.service';
import { MesInfosService } from './mesInfos.service';
export * from './rglements.service';
import { RglementsService } from './rglements.service';
export * from './tiers.service';
import { TiersService } from './tiers.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [ArticlesService, AuthenticationService, BonsAchatVenteService, CaisseJourControllerService, DettesControllerService, FluxNormalControllerService, MesInfosService, RglementsService, TiersService, UserControllerService];
