services:
  angular-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network


networks:
  app-network:
    external: true
