/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Article { 
    cod?: number;
    ref?: number;
    famille?: string;
    designation?: string;
    choix?: string;
    reference?: string;
    stock?: number;
    surfaceUnitaire?: number;
    surface?: number;
    stockAlert?: number;
    prixAchat?: number;
    prixMin?: number;
    prix?: number;
    remise?: number;
    controle?: string;
    note?: string;
    achatHt?: number;
    tauxTva?: number;
    margeFact?: number;
    venteHt?: number;
    stockFact?: number;
    classe?: string;
    stockMax?: number;
    pack?: number;
    actif?: boolean;
    marge1?: number;
    marge2?: number;
    barCode?: string;
    rayon?: string;
    noStock?: boolean;
    createdAt?: string;
}

