/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleDto { 
    cod?: number;
    ref?: number;
    designation?: string;
    prix?: number;
    prixMin?: number;
    prixAchat?: number;
    tauxTva?: number;
    note?: string;
    choix?: string;
    stock?: number;
    famille?: string;
    quantite?: number;
    idTier?: number;
}

