/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleAddBonDto } from './articleAddBonDto';


export interface BonAchatVenteDto { 
    idBon?: number;
    serie?: string;
    montant?: number;
    montantSansRemise?: number;
    espece?: number;
    cheque?: number;
    credit?: number;
    remis?: number;
    remisSurBon?: number;
    detCheque?: string;
    datBon?: string;
    idTier?: number;
    nomTier?: string;
    idUser?: number;
    nomUser?: string;
    mvt?: string;
    articles?: Array<ArticleAddBonDto>;
}

