/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Tier } from './tier';
import { Flux } from './flux';


export interface Bonsorti { 
    idBon?: number;
    serie?: string;
    mvt?: Bonsorti.MvtEnum;
    tier?: Tier;
    datBon?: string;
    montant?: number;
    espece?: number;
    cheque?: number;
    detCheq?: string;
    echeance?: string;
    credit?: number;
    etat?: boolean;
    remis?: number;
    livraison?: string;
    origine?: string;
    noom?: string;
    reglements?: string;
    user?: User;
    dateOpp?: string;
    marche?: string;
    transport?: string;
    note01?: string;
    valid?: boolean;
    fluxes?: Array<Flux>;
    mht?: number;
    mremis?: number;
    mtva?: number;
}
export namespace Bonsorti {
    export const MvtEnum = {
        Achat: 'ACHAT',
        Vente: 'VENTE'
    } as const;
    export type MvtEnum = typeof MvtEnum[keyof typeof MvtEnum];
}


