/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BonSortieDto { 
    idBon?: number;
    serie?: string;
    montant?: number;
    espece?: number;
    cheque?: number;
    credit?: number;
    datBon?: string;
    nomTier?: string;
    nomUser?: string;
}

