/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonSortieDto } from './bonSortieDto';


export interface CaisseJourDto { 
    date?: string;
    bons?: Array<BonSortieDto>;
    totalMontant?: number;
    totalEspece?: number;
    totalCheque?: number;
    totalCredit?: number;
    nomUser?: string;
}

