/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonSortieDto } from './bonSortieDto';
import { ReglementDto } from './reglementDto';


export interface CaisseJourDto { 
    date?: string;
    bonsAchat?: Array<BonSortieDto>;
    bonsVente?: Array<BonSortieDto>;
    totalMontant?: number;
    totalEspece?: number;
    totalCheque?: number;
    totalCredit?: number;
    nomUser?: string;
    reglements?: Array<ReglementDto>;
}

