/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DettesDto { 
    idTier?: number;
    nomTier?: string;
    chiffreAnnuelle?: number;
    detteFinal?: number;
    taux?: number;
    qualite?: DettesDto.QualiteEnum;
    dateRegl?: string;
}
export namespace DettesDto {
    export const QualiteEnum = {
        Client: 'CLIENT',
        Fournisseur: 'FOURNISSEUR',
        Mixte: 'MIXTE'
    } as const;
    export type QualiteEnum = typeof QualiteEnum[keyof typeof QualiteEnum];
}


