/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FluxNormalDto } from './fluxNormalDto';


export interface FluxNormalResponseDto { 
    stockInitial?: number;
    fluxes?: Array<FluxNormalDto>;
    dateInitial?: string;
    totalEntres?: number;
    totalSorties?: number;
}

