/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bonsorti } from './bonsorti';
import { Article } from './article';


export interface Flux { 
    idFlux?: number;
    libelle?: string;
    bonSorti?: Bonsorti;
    dateFlux?: string;
    article?: Article;
    ref?: number;
    entree?: number;
    sortie?: number;
    prixUni?: number;
    montant?: number;
    cout?: number;
    mesure?: string;
    surfE?: number;
    surfS?: number;
    surfU?: number;
    plat?: number;
    txTva?: number;
    fremis?: number;
    ttva?: number;
}

