/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MesInfoxDto { 
    num?: number;
    nomSociete?: string;
    activite?: string;
    adresse?: string;
    piedPage?: string;
    serial?: string;
    note01?: string;
    note02?: string;
    blogo?: string;
    flogo?: string;
    fcod?: string;
    bnom?: string;
    bserial?: string;
    bactivite?: string;
    badresse?: string;
    bcod?: string;
}

