/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageResponse { 
    content?: Array<any>;
    currentPage?: number;
    totalPages?: number;
    totalElements?: number;
    pageSize?: number;
}

