/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    username?: string;
    gsm?: string;
    password?: string;
    role?: RegisterRequest.RoleEnum;
}
export namespace RegisterRequest {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


