/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Tier } from './tier';


export interface Reglement { 
    idRegl?: number;
    datRegl?: string;
    mouvement?: Reglement.MouvementEnum;
    tier?: Tier;
    user?: User;
    total?: number;
    espece?: number;
    cheque?: number;
    det_cheque?: string;
}
export namespace Reglement {
    export const MouvementEnum = {
        Achat: 'ACHAT',
        Vente: 'VENTE'
    } as const;
    export type MouvementEnum = typeof MouvementEnum[keyof typeof MouvementEnum];
}


