/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReglementDto } from './reglementDto';


export interface ReglementResponseDto { 
    reglements?: Array<ReglementDto>;
    totalEspece?: number;
    totalCheque?: number;
}

