/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReglementDto { 
    id?: number;
    idTier?: number;
    idUser?: number;
    nomTier?: string;
    nomUser?: string;
    espece?: number;
    cheque?: number;
    detailsCheque?: string;
    datRegl?: string;
    reglement?: number;
    totalEspece?: number;
    totalCheque?: number;
}

