/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TierDto { 
    id?: number;
    qualite: string;
    type?: string;
    ref: number;
    nom: string;
    nif?: string;
    patent?: string;
    nrc?: string;
    cin?: string;
    adresse: string;
    ville: string;
    fon: string;
    gsm?: string;
    fax?: string;
    banq?: string;
    numCompte?: string;
    solde?: number;
    note?: string;
    plafond?: number;
    soldeFact?: number;
    cremise?: number;
}

