/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Reglement } from './reglement';


export interface Tier { 
    id?: number;
    qualite?: Tier.QualiteEnum;
    actif?: boolean;
    type?: string;
    ref?: number;
    nom?: string;
    nif?: string;
    patent?: string;
    nrc?: string;
    cin?: string;
    adresse?: string;
    ville?: Tier.VilleEnum;
    fon?: string;
    gsm?: string;
    fax?: string;
    banq?: string;
    numCompte?: string;
    solde?: number;
    note?: string;
    plafond?: number;
    soldeFact?: number;
    reglements?: Array<Reglement>;
    cremise?: number;
}
export namespace Tier {
    export const QualiteEnum = {
        Client: 'CLIENT',
        Fournisseur: 'FOURNISSEUR',
        Mixte: 'MIXTE'
    } as const;
    export type QualiteEnum = typeof QualiteEnum[keyof typeof QualiteEnum];
    export const VilleEnum = {
        Casablanca: 'CASABLANCA',
        Rabat: 'RABAT',
        Marrakech: 'MARRAKECH',
        Fes: 'FES',
        Tanger: 'TANGER',
        Agadir: 'AGADIR',
        Meknes: 'MEKNES',
        Oujda: 'OUJDA',
        Kenitra: 'KENITRA',
        Sale: 'SALE',
        ElJadida: 'EL_JADIDA',
        Safi: 'SAFI',
        Benguerir: 'BENGUERIR',
        Settat: 'SETTAT',
        Khouribga: 'KHOURIBGA',
        Tetouan: 'TETOUAN',
        Nador: 'NADOR',
        AlHoceima: 'AL_HOCEIMA',
        KelaaDesSrair: 'KELAA_DES_SRAIR',
        Taza: 'TAZA',
        Berkane: 'BERKANE',
        Khribga: 'KHRIBGA',
        Bouznika: 'BOUZNIKA',
        BeniMellal: 'BENI_MELLAL',
        Ouarzazate: 'OUARZAZATE',
        Dakhla: 'DAKHLA',
        Larache: 'LARACHE',
        Gueznaya: 'GUEZNAYA',
        AlAyoubia: 'AL_AYOUBIA',
        Saida: 'SAIDA',
        Tifnit: 'TIFNIT',
        Zagora: 'ZAGORA',
        Errakaa: 'ERRAKAA',
        SidiKacem: 'SIDI_KACEM',
        Youssoufia: 'Youssoufia',
        SidiSltan: 'SIDI_SLTAN',
        Tangier: 'TANGIER',
        Taznalt: 'TAZNALT',
        Imilchil: 'IMILCHIL',
        Midelt: 'MIDELT',
        Azilal: 'AZILAL',
        BeniAbbes: 'BENI_ABBES',
        MarrakechMenara: 'MARRAKECH_MENARA',
        MarrakechMedina: 'MARRAKECH_MEDINA',
        OujdaMedina: 'OUJDA_MEDINA',
        Tiznit: 'TIZNIT',
        Essaouira: 'ESSAOUIRA',
        Tahanaout: 'TAHANAOUT',
        Taharsa: 'TAHARSA',
        TangierMed: 'TANGIER_MED'
    } as const;
    export type VilleEnum = typeof VilleEnum[keyof typeof VilleEnum];
}


