/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BonSortieDto } from './bonSortieDto';
import { ReglementDto } from './reglementDto';


export interface TierStatistiqueCreditDto { 
    tierId?: number;
    nomTier?: string;
    bonsorties?: Array<BonSortieDto>;
    reglements?: Array<ReglementDto>;
    totalCredit?: number;
    totalDebit?: number;
    resteAPayer?: number;
    percentageDebitCredit?: number;
}

