/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bonsorti } from './bonsorti';
import { Reglement } from './reglement';


export interface User { 
    cod?: number;
    login?: string;
    pass?: string;
    role?: string;
    depot?: number;
    gsm?: string;
    note1?: string;
    note2?: string;
    note3?: string;
    etat?: string;
    bonsSortis?: Array<Bonsorti>;
    reglements?: Array<Reglement>;
}

